### ISSUE TITLE
Grpcc failed with " UNAVAILABLE: TCP Read failed"

### ISSUE THREAD

**Issue by mgolovatiy-atconsulting-ru** [lagom/lagom-samples#89] opened 2019-08-08 13:05 UTC
Need help with some weird exception occured during testing grpc methods.

Testing "_lagom-java-grpc-example_", run _ssl-lagom_ , then runAll command.
Http-GET requests via _curl_ succeeded.
Tried to invoke grpc-method.
Grpcc console taken from **njpatel/grpcc** github repo.
Ran grpcc as pointed in README- had error. Can connect to service, but when tried to invoke `client.sayHello("Alice", printReply)` had the same exception.

Connecting:
`grpcc --proto hello-impl/src/main/protobuf/helloworld.proto --insecure --address 127.0.0.1:11000`
Connected:
``` 
Connecting to helloworld.GreeterService on 127.0.0.1:11000. Available globals:

  client - the client connection to GreeterService
    sayHello (HelloRequest, callback) returns HelloReply

  printReply - function to easily print a unary call reply (alias: pr)
  streamReply - function to easily print stream call replies (alias: sr)
  createMetadata - convert JS objects into grpc metadata instances (alias: cm)
  printMetadata - function to easily print a unary call's metadata (alias: pm)
```
Method invoked- exception:

```
Error:  { Error: 14 UNAVAILABLE: TCP Read failed
    at Object.exports.createStatusError (C:\Users\abcdef\AppData\Roaming\npm\node_modules\grpcc\node_modules\grpc\src\common.js:91:15)
    at Object.onReceiveStatus (C:\Users\abcdef\AppData\Roaming\npm\node_modules\grpcc\node_modules\grpc\src\client_interceptors.js:1204:28)
    at InterceptingListener._callNext (C:\Users\abcdef\AppData\Roaming\npm\node_modules\grpcc\node_modules\grpc\src\client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (C:\Users\abcdef\AppData\Roaming\npm\node_modules\grpcc\node_modules\grpc\src\client_interceptors.js:618:8)
    at callback (C:\Users\abcdef\AppData\Roaming\npm\node_modules\grpcc\node_modules\grpc\src\client_interceptors.js:845:24) code: 14, metadata: {}, details: 'TCP Read failed' }
```

Also made my project on maven, mostly copied from sample (Maven 3.6.0, java 1.8, x64, Win7). Have the same error. 

May be some additional configuration needed? Or other grpc CLI?

**Comment by ignasi35** [comment] 2019-08-22 15:22
Hi @mgolovatiy-atconsulting-ru , I suspect the issue is related to trying to run `grpcc` with `--insecure`. I've just run the following locally:


```
$ grpcc --proto hello-impl/src/main/protobuf/helloworld.proto           --address localhost:11000           --eval 'client.sayHello({name:"Katherine"}, printReply)'           --root_cert ./trustedCA.pem
(node:56120) DeprecationWarning: grpc.load: Use the @grpc/proto-loader module with grpc.loadPackageDefinition instead
{
  "message": "Hi Katherine (gRPC)"
}
ignasi at imslightbend in ~/git/projects/lightbend/lagom/lagom-samples/grpc-example/grpc-example-java on 1.5.x*
$ grpcc --proto hello-impl/src/main/protobuf/helloworld.proto           --address localhost:11000           --eval 'client.sayHello({name:"Katherine"}, printReply)'           --insecure(node:56208) DeprecationWarning: grpc.load: Use the @grpc/proto-loader module with grpc.loadPackageDefinition instead
Error:  { Error: 14 UNAVAILABLE: TCP Read failed
    at Object.exports.createStatusError (/usr/local/lib/node_modules/grpcc/node_modules/grpc/src/common.js:91:15)
    at Object.onReceiveStatus (/usr/local/lib/node_modules/grpcc/node_modules/grpc/src/client_interceptors.js:1204:28)
    at InterceptingListener._callNext (/usr/local/lib/node_modules/grpcc/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/usr/local/lib/node_modules/grpcc/node_modules/grpc/src/client_interceptors.js:618:8)
    at callback (/usr/local/lib/node_modules/grpcc/node_modules/grpc/src/client_interceptors.js:845:24) code: 14, metadata: {}, details: 'TCP Read failed' }
```

I just realised there was an issue in the docs ([which I fixed on this PR](https://github.com/lagom/lagom-samples/pull/91#pullrequestreview-278498987)) making it difficult to extract the `trustedCA.pem` required to use `grpcc` in _secure_ mode.

**Comment by mgolovatiy-atconsulting-ru** [comment] 2019-08-23 09:47
Excellent. It works. Used `selfsigned.keystore`.

**Closed as completed** 2019-08-23 13:20 UTC
